apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-group2-pedidos-db-svc-np
  namespace: 'tech-challenge-group2-pedidos'
spec:
  selector:
    app: tech-challenge-group2-pedidos-db-deployment
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: NodePort
