apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-group2-pedidos-svc-np
  namespace: 'tech-challenge-group2-pedidos'
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30000
  selector:
    app: tech-challenge-group2-pedidos